### PR TITLE
Closes #2; updated README with demo

### LINKED ISSUE #2: Add a demo
Add a simple page where users can the test lib.

### PR DESCRIPTION
**Pull request by aulisius**
Currently used the basic form example from bootstrap. Is this enough? Or should I use a more complex example?

### CODE REVIEW

**Comment by aulisius** [comment]
Sure. sounds good. I'll get on it!

**Comment by aulisius** [comment]
So, I turned into a credit card form. Can you go through it and see if it looks good?

**Comment by damienalexandre** [comment]
Almost good! 

The maxlenght attribute is not very well supported with the input type "number", so if I keep pressed <kbd>1</kbd>, the input is never stopped. We use `<input type="tel"` in production to avoid those issues.

And finally, there is some remaining occurrences of "password" in the labels and other attributes.

**Comment by aulisius** [comment]
TIL. Never knew about differences between `type=tel` and `type=number`. I've updated those now. Finally, for the CVV I've kept `type=password` because it is sensitive info.

**Comment by damienalexandre** [comment]
Awesome work, thank you very much :+1:

**Pull request merged**
